# Generated by Django 4.0.6 on 2022-08-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEmpresa', models.CharField(max_length=180, unique=True, verbose_name='Empresa')),
                ('NIT', models.CharField(max_length=180, unique=True, verbose_name='NIT')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='idEmpresa',
            field=models.IntegerField(default=1),
        ),
    ]
