# Generated by Django 4.0.6 on 2022-07-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=1, help_text='Ingresa la el nombre', max_length=500, verbose_name='nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(help_text='Ingresa la descripcion del producto', max_length=500, verbose_name='descripcion'),
        ),
    ]
