# Generated by Django 4.0.6 on 2022-08-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_empresa_producto_idempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='authApp.empresa'),
        ),
    ]
