# Generated by Django 4.0.6 on 2022-07-30 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_remove_categoria_nombrecategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.proveedor'),
        ),
    ]
