# Generated by Django 4.0.6 on 2022-07-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_producto_idcategoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='idCategoria',
            new_name='Categoria_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='idProducto',
            new_name='Producto_id',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='idProveedor',
            new_name='Proveedor_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idProveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='authApp.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='authApp.proveedor'),
            preserve_default=False,
        ),
    ]
