# Generated by Django 4.0.6 on 2022-08-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_producto_idempresa'),
        ('authApp', '0006_alter_producto_nombre_alter_usuario_email'),
    ]

    operations = [
    ]
