# Generated by Django 4.0.6 on 2022-08-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_merge_20220801_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='idEmpresa',
            new_name='Empresa_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='idEmpresa',
            new_name='Empresa',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='Username',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='cedula',
            new_name='Usuario_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Cedula',
            field=models.CharField(default=1, max_length=20, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
