# Generated by Django 4.0.6 on 2022-08-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_rename_idempresa_empresa_empresa_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Password',
            field=models.CharField(default=1, max_length=256, verbose_name='Password'),
        ),
    ]
