# Generated by Django 4.0.6 on 2022-08-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Cedula',
            field=models.CharField(default=0, max_length=20, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Password',
            field=models.CharField(max_length=256, verbose_name='Password'),
        ),
    ]
