# Generated by Django 4.0.6 on 2022-08-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0010_alter_usuario_cedula_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='Usuario',
            name='Empresa_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_id', to='authApp.empresa'),
        ),
    ]
