# Generated by Django 4.0.6 on 2022-08-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_usuario_empresa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Empresa_id',
            new_name='Empresa',
        ),
    ]
