# Generated by Django 4.0.6 on 2022-08-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0013_alter_usuario_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
