# Generated by Django 4.0.6 on 2022-08-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0014_alter_usuario_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Username'),
        ),
    ]
