# Generated by Django 4.0.6 on 2022-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0016_remove_usuario_password_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
