# Generated by Django 4.0.6 on 2022-08-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0017_remove_usuario_password_alter_usuario_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuario_id',
            new_name='id',
        )
    ]
