# Generated by Django 4.0.6 on 2022-08-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0018_rename_usuario_id_usuario_id_remove_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Empresa',
            new_name='idEmpresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Password',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='NombreEmpresa',
            field=models.CharField(max_length=180, unique=True, verbose_name='NombreEmpresa'),
        ),
    ]
