# Generated by Django 4.0.6 on 2022-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0018_rename_usuario_id_usuario_id_remove_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Username',
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField( max_length=30, unique=True, verbose_name='username'),
        ),
    ]
