# Generated by Django 4.0.6 on 2022-08-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0020_rename_idempresa_producto_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Empresa',
            new_name='idEmpresa',
        ),
    ]
