from .ProductoCreateView import ProductoCreateView
from .ProductoDetailView import ProductoDetailView
from .ProductoAllView import ProductoAllView
from .ProveedorCreateView import ProveedorCreateView
from .ProveedorDetailView import ProveedorDetailView
from .EmpresaCreateView import EmpresaCreateView
from .EmpresaDetailView import EmpresaDetailView
